name: docs

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: prepare
      run: cp ./README.md ./docs/.
    - name: Install needed packages
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs "mkdocstrings[python]"
    - name: build the docs
      run: mkdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./site
